// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai/match': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/match.get').default>>>>
    }
    '/api/ai/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/search.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/claims': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/claims/index.post').default>>>>
    }
    '/api/claims/my': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/claims/my.get').default>>>>
    }
    '/api/comments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comments/index.post').default>>>>
    }
    '/api/likes/comment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/likes/comment.post').default>>>>
    }
    '/api/likes/post': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/likes/post.post').default>>>>
    }
    '/api/notifications/:id/read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/[id]/read.post').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/notifications/read-all': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/read-all.post').default>>>>
    }
    '/api/notifications/stream': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/stream.get').default>>>>
    }
    '/api/posts/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/[id].get').default>>>>
    }
    '/api/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
  }
}
export {}